"$schema" = 'https://starship.rs/config-schema.json'

# colors
# #3960A7 - dark blue
# #659CD9 - mid blue
# #4A4A4A - dary grey
# #F2F2F2 - near white
# #9C9C9C - mid gray

format = """\
[](fg:#659CD9)\
$os\
$sudo\
$shell\
[](fg:#659CD9 bg:#3960A7)\
$directory\
[](fg:#3960A7 bg:#9C9C9C)\
$git_branch\
$git_commit\
$git_status\
$git_state\
[](fg:#9C9C9C bg:#F2F2F2)\
($git_metrics)\
[](fg:#F2F2F2)\
$fill\
$status\
$all\
$cmd_duration\
$line_break\
$character"""

# disabled due to fill module
# right_format = ''
add_newline = true
# command_timeout = 1000

[line_break]
disabled = false

[fill]
symbol = ' '

[os]
disabled = false
format = '[$symbol]($style)'
style = 'fg:#659CD9 bg:#F2F2F2 inverted'

[os.symbols]
Macos = " "
Windows = " "
Ubuntu = " "

[sudo]
disabled = false
symbol = "🧙"
format = '[$symbol ]($style)'
style = "bg:#C2B4DF"

[shell]
disabled = false
zsh_indicator = ''
powershell_indicator = ''
style = 'fg:#F2F2F2 bg:#659CD9'
format = '[$indicator ]($style)'

[directory]
format = "[ \uf07c  $path ]($style)"
style = "fg:#F2F2F2 bg:#3960A7"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "  "
style = "fg:#1C3A5E bg:#9C9C9C"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
style = "fg:#1C3A5E bg:#9C9C9C"

[git_commit]
disabled = false
format = '[\((#$hash)$tag\)]($style)'
tag_disabled = false
only_detached = true
style = "fg:#1C3A5E bg:#9C9C9C"

[git_metrics]
format = '([ +$added ]($added_style))([-$deleted ]($deleted_style))'
added_style = "fg:#1C3A5E bg:#F2F2F2"
deleted_style = "fg:red bg:#F2F2F2"
disabled = false

[cmd_duration]
disabled = false
format = "[[](fg:#5C7F6A)⏱️ $duration[](fg:#5C7F6A)]($style)"
style = "#5C7F6A inverted"

[character]
disabled = false
success_symbol = '[❯](bold #F2F2F2) '
error_symbol = '[❯](bold red) '

[time]
disabled = true
time_format = "%R"                                      # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ 󱑍 $time ](bg:#1C3A5E fg:#8DFBD2)]($style)'

[azure]
disabled = false
format = '[](fg:#3376CD)[$symbol($subscription)]($style)[](fg:#3376CD)'
style = 'fg:#3376CD bold inverted'
symbol = '󰠅 '

[golang]
disabled = true
format = '[](fg:cyan)[$symbol($version )]($style)[](fg:cyan)'
style = 'fg:cyan inverted'
symbol = ' '

[status]
disabled = false
symbol = '🔴 '
success_symbol = ''
format = '[$symbol( $common_meaning )$signal_name$maybe_int]($style) '
map_symbol = true

[terraform]
symbol = '󱁢 '
#format = '[](fg:105)[$symbol$version( $workspace)]($style)[](fg:105)'
format = '[](fg:105)[$symbol]($style)[](fg:105)'
style = 'fg:105 inverted'

[hostname]
disabled = true

[kubernetes]
disabled = true

[pulumi]
disabled = true

[aws]
disabled = true

[buf]
disabled = true

[bun]
disabled = true

[c]
disabled = true

[cmake]
disabled = true

[cobol]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[daml]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[fennel]
disabled = true

[gcloud]
disabled = true

[guix_shell]
disabled = true

[gradle]
disabled = true

[haskell]
disabled = true

[haxe]
disabled = true

[helm]
disabled = true

[java]
disabled = true

[jobs]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[localip]
disabled = true

[lua]
disabled = true

[meson]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[opa]
disabled = true

[openstack]
disabled = true

[package]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[pijul_channel]
disabled = true

[purescript]
disabled = true

[python]
disabled = true

[quarto]
disabled = true

[rlang]
disabled = true

[raku]
disabled = true

[red]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[shlvl]
disabled = true

[singularity]
disabled = true

[solidity]
disabled = true

[spack]
disabled = true

[swift]
disabled = true

[typst]
disabled = true

[vagrant]
disabled = true

[vlang]
disabled = true

[vcsh]
disabled = true

[zig]
disabled = true
